apiVersion: apps/v1
kind: Deployment
metadata:
    name: capstone-project
    labels:
        app: capstone-project
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: capstone-project
    strategy:
        rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: capstone-project
        spec:
            containers:
                - image: markanradanovic/capstone-project
                  imagePullPolicy: Always
                  name: capstone-project
                  ports:
                      - containerPort: 80
                        name: capstone
                          
---

apiVersion: v1
kind: Service
metadata:
    name: capstone-project
    labels:
        app: mycapstone
spec:
    selector:
        app: capstone-project
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80