apiVersion: apps/v1
kind: Deployment
metadata:
    name: UdacityCapstone
    labels:
        app: UdacityCapstone
    namespace: default
spec:
    replicas: 2
    selector:
        matchLabels:
            app: UdacityCapstone
    strategy:
        rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: UdacityCapstone
        spec:
            containers:
                - image: markanradanovic/UdacityCapstone
                    imagePullPolicy: Always
                    name: UdacityCapstone
                    ports:
                        - containerPort: 80
                          name: UdacityCapstonePort
                          

apiVersion: v1
kind: Service
metadata:
    name: CapstoneService
spec:
    selector:
        app: UdacityCapstone
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80